name: 'Auto Label'

on:
  pull_request_target:


jobs:
  auto-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        configuration-path: .github/auto-label.yml
