name: Docker Image CI

on:
    pull_request:
        branches: ['dev']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: 读取仓库的内容
              uses: actions/checkout@v4

            - name: 登陆 Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: 构建并推送到 Push to Docker Hub
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: aminnausin/mediaserver:beta
