name: Docker Image CI

on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Release Tag'
                required: true
    # push:
    #     branches: ['dev']

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: 读取仓库的内容
              uses: actions/checkout@v4

            - name: Replace DOCKER_RELEASE in .env.docker
              run: |
                  sed -i "s/DOCKER_RELEASE=.*/DOCKER_RELEASE=beta/" docker/.env.docker

            - name: 登陆 Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: 构建并推送到 Push to Docker Hub
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: aminnausin/mediaserver:beta

            - name: Zip Files Linux
              run: |
                  zip -r mediaServerDockerLinuxBeta.zip ./docker/etc ./docker/.env.docker ./docker-compose.yaml ./startDocker.sh ./README.md ./data/avatars

            - name: Zip Files Windows
              run: |
                  zip -r mediaServerDockerWindowsBeta.zip ./docker/etc ./docker/.env.docker ./docker-compose.yaml ./startDocker.bat ./README.md ./data/avatars
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: true
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag: 'beta'
                  name: Beta Release
                  draft: false
                  prerelease: false
                  artifacts: mediaServerDockerLinuxBeta.zip,mediaServerDockerWindowsBeta.zip
