name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      release:
        description: "yes to release"
        required: false

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库的内容
      uses: actions/checkout@v4
      
    - name: 登陆Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: 构建并推送到Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: suyiyi/mediaserver:latest
